package pack.plantecompagnon.src;

public enum ProblemTypeList {
    ACCLIMATATION_DIFFICILE,
    DESEQUILIBRES_NUTRITIONNELS,
    DOMMAGES_PHYSIQUES,
    HUMIDITE_INSUFFISANTE,
    INFESTATIONS_DE_PARASITES,
    MALADIES_BACTERIENNES,
    MALADIES_FONGIQUES,
    MANQUE_DE_LUMIERE,
    SOUS_ARROSAGE,
    STRESS_HYDRIQUE,
    SUR_ARROSAGE,
    TEMPERATURE_INAPPROPRIEE,
    TOXICITE,
    TROP_DE_LUMIERE,
    AUTRE
}